[package]
name = "bevy_previous_derive"
version = "1.0.0"
edition = "2021"
description = "proc_macros for bevy_previous"
repository = "https://github.com/bnjmn21/bevy_previous"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.74"
